server:
  port: 8085
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZeroXD219/pea4.git
          searchPaths: config-data
          username: andyllamodiaz@gmail.com
          password: 123Andy123@
          default-label: "main"
  security:
    user:
      name: io
      password: 123
